(use-package paredit
  :ensure t)
(use-package ido-ubiquitous
  :ensure t)
(use-package helm-smex
  :ensure t)
(use-package projectile
  :ensure t)
(use-package rainbow-delimiters
  :ensure t)
(use-package undo-tree
  :ensure t
  :pin gnu)
(use-package xclip
  :ensure t)
(use-package decide
  :ensure t)
(use-package emmet-mode
  :ensure t)
(use-package web-mode
  :ensure t)
(use-package js2-mode
  :ensure t
  :pin melpa)
(use-package flycheck
  :ensure t)
(use-package slime
  :ensure t)
(use-package evil
  :ensure t
  :pin melpa)
(use-package lsp-java
  :ensure t)
